### ISSUE TITLE
[FEATURE] Make Shuffleboard UI ergonomic and useful

### ISSUE THREAD

**Issue by WilliamBehrens** [rr1706/Control2022#22]

**Comment by Mason-Schulte** [comment]
Are we still going to incorporate Scouting into our shuffleboard?

**Comment by WilliamBehrens** [comment]
@Mason-Schulte After talking with Ian we decided it would be better to have that data easily viewable in the scouting app rather then the dashboard as it would be easier to look at it pre-game
